repos:
  - repo: local
    hooks:
      - id: merge_file
        name: merge file
        entry: ./merge_file.bash
        language: script
        types: [python]
        pass_filenames: false
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff
