[tools]
pre-commit = "4.2.0"
uv = "0.6.17"
python = "3.13.3"

[tasks]
install = "uv sync && mise generate git-pre-commit --write --task=pre_commmit_task"

[tasks.pre-commit]
run = "./pre_commit.bash"
