[tools]
pre-commit = "4.2.0"
uv = "0.7.2"
python = "3.13.3"

[tasks]
install = "uv sync && mise generate git-pre-commit --write --task=pre-commit"

[tasks.pre-commit]
run = "./pre_commit.bash"

[settings]
python.uv_venv_auto = true

[env]
_.python.venv = { path = ".venv" }
