[tools]
pre-commit = "4.2.0"
uv = "0.6.17"
python = "pypy3.10-7.3.17"

[tasks]
install = "uv sync && mise generate git-pre-commit --write --task=pre-commit"

[tasks.pre-commit]
run = "./pre_commit.bash"
