[tools]
uv = "0.8.0"
python = "3.13.5"

[tasks]
install = "uv sync && mise generate git-pre-commit --write --task=pre-commit"

[tasks.pre-commit]
run = "./pre_commit.bash"

[env]
_.python.venv = { path = ".venv" }
PYTHONPATH = "."

