name: merge split files

on:
  push

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: merge split files
      run: |
        chmod +x ./merge_file.bash
        ./merge_file.bash

    - name: Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Merge split file by actions
