name: run merge split files and format

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  merge_file:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}


    - name: merge split files
      run: |
        chmod +x ./merge_file.bash
        ./merge_file.bash

    - name: Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Merge split file by actions

  format_file:
    runs-on: ubuntu-latest
    needs: [merge_file]
    permissions:
      contents: write

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Check Python Version
      run: python -V

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Run Ruff
      run: ruff format .

    - name: Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Format File By Actions
