name: run unittest

on:
  pull_request:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 'pypy3.10'

    - name: Check Python Version
      run: python -V

    - name: Run Test
      run: python test.py
