name: run unittest
on:
  push:
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: install mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
          mise install
      # - name: Setup Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: 'pypy3.10'
      - name: Check Python Version
        run: python -V
      - name: Run Test
        run: mise run test
