name: unittest and merge split files

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  run_unittest:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 'pypy3.10'

    - name: Check Python Version
      run: python -V

    - name: Run Test
      run: python test.py
      
  merge_file:
    runs-on: ubuntu-latest
    needs: [run_unittest]
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}


    - name: merge split files
      run: |
        chmod +x ./merge_file.bash
        ./merge_file.bash

    - name: "Import GPG key"
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Merge split file by actions
        commit_author: "${{ steps.import-gpg.outputs.name }} <${{ steps.import-gpg.outputs.email }}>"
        commit_user_name: ${{ steps.import-gpg.outputs.name }}
        commit_user_email: ${{ steps.import-gpg.outputs.email }}

  format_file:
    runs-on: ubuntu-latest
    needs: [merge_file]
    permissions:
      contents: write

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Check Python Version
      run: python -V

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Run Ruff
      run: ruff format .


    - name: "Import GPG key"
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Format File By Actions
        commit_author: "${{ steps.import-gpg.outputs.name }} <${{ steps.import-gpg.outputs.email }}>"
        commit_user_name: ${{ steps.import-gpg.outputs.name }}
        commit_user_email: ${{ steps.import-gpg.outputs.email }}
        commit_options: '-S --amend --no-edit'
